### PR TITLE
Update examples to match apache repo.

### PR DESCRIPTION
**Pull request by robertwb**
Snapshot at commit 0cabdf6e776363e639f18779744da73f9d29bb5a.

### CODE REVIEW

**Comment by davorbonaci** [comment]
I'm not sure what this PR is intended to do, but we normally update the examples only when we are doing a release. We could do it more often if necessary, but we didn't usually.

**Comment by aaltay** [comment]
This repo contains examples that matches the released binaries. This change will break the test as not all of the updated examples can run agains the 2.0.0 version of the package.

**Comment by robertwb** [comment]
Examples are widely copied/emulated. The primary motivation was to move to the less error-prone pipeline-as-a-context syntax (which was introduced well before 2.0.0). 

I synced back to a commit before apache_beam.testing.util.open_shards was used/introduced.

**Comment by aaltay** [comment]
It sounds good to me to move to pipeline as a context syntax. 

I believe this change will also fail. Because test code is running against the released version (e.g. `from apache_beam.examples.cookbook import group_with_coder`).

**Comment by robertwb** [comment]
Oh, that's somewhat counter-productive. Filed https://issues.apache.org/jira/browse/BEAM-2474 and reverted the offending tests.

**Comment by aaltay** [comment]
LGTM.

I believe the JIRA issue should be a Github issue in the repo. We can fix that by having a release script in this repo, which copies examples and re-write the imports.

**Comment by robertwb** [comment]
Filed in issue in this repo. (Not sure who triages or even looks at these
issues.)

**Comment by aaltay** [comment]
Thank you. @davorbonaci and I, we go over the issues and open PRs in this repo and other dataflow repositories weekly.

**Pull request merged**
